# NUMPY

In [1]:
import numpy as np

#### axis- a direction(row vs columes)
#### shape- size in each axis,
#### dtype-the single data 
##### np.arange(0,10,2) same as range
##### np.linspace(0,1,5) 


In [3]:
marks=np.array([78,85,90,67,88])
print(marks)

[78 85 90 67 88]


In [4]:
age=np.array([20,21,19,23,21])
print(age)
print(marks.dtype)

[20 21 19 23 21]
int64


In [8]:
arr=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(arr)
print(arr[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]


##### for slicing -----arr[row,colume]
##### for range with specific row or colume ---arr[start row : end row , start colume : end colume]

In [9]:
arr[1,2]

np.int64(6)

In [10]:
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### for the dimention

In [20]:

arr.ndim

2

In [21]:
data=np.arange(12)
data.reshape(3,4)
data.reshape(4,3)



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
data.reshape(5,2)

ValueError: cannot reshape array of size 12 into shape (5,2)

#### convert 2d to 1d

In [19]:

arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Element- Wise Math-- Arrae vs Array

In [23]:
a=np.array([1,2,3])
b=np.array([10,20,30])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]


### array mathe in different array size

In [25]:
a=np.array([1,2,3,4])
b=np.array([10,20,30])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

Array vs Scalar

In [28]:

b=np.array([10,20,30])
print(b+5)
print(b*2)
print(b/10)
print(b**2)

print(b**0.5)

[15 25 35]
[20 40 60]
[1. 2. 3.]
[100 400 900]
[3.16227766 4.47213595 5.47722558]


In [30]:
print(b.sum())
print(b.mean())
print(b.max())
print(b.min())
print(b.std())

60
20.0
30
10
8.16496580927726


### Aggregation Along an Axis

In [31]:
arr2=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(arr2.sum())
print(arr2.sum(axis=0))
print(arr2.sum(axis=1))

45
[12 15 18]
[ 6 15 24]


In [37]:
marks2=np.array([72,88,95,64,79,90,58])
print(marks2.mean())
print(marks2.max())
print(marks2.min())
for i in marks2:
    if i>marks2.mean():
        print("bonus",i)

# Or
bonus=marks2>marks2.mean()
print(bonus)


78.0
95
58
bonus 88
bonus 95
bonus 79
bonus 90
[False  True  True False  True  True False]


### What is Broadcasting = numpy automatically stretch a small array to match a bigger one- so they can do math together
#### save memory- the small array isn't really copied,just reused
#### save code- no loop to repeat values
#### save time- it runs on fast c

### The Simple Rules
#### A scalar work with any array
#### A row can ad to every row of a matrix
#### Size must match or one of them is 1
##### (2,3) + (1,3) correct but (2,3) + (2,) wronge

In [39]:
m=np.array([[1,2,3],[4,5,6]])
# shap (3,) fits each row of a (2,3)
row= np.array([10,20,30])
m+row

array([[11, 22, 33],
       [14, 25, 36]])

# EASY

In [42]:
marks=np.array([78,85,90,67,88])
print(marks)
age=np.array([20,21,19,23,21])
print(age)
print(marks.dtype,age.dtype)
print(marks.shape,age.shape)
print(marks.ndim,age.ndim)
print(marks.max(),age.max())
print(marks.mean(),age.mean())

[78 85 90 67 88]
[20 21 19 23 21]
int64 int64
(5,) (5,)
1 1
90 23
81.6 20.8


# ADVANCED

In [ ]:
print(marks.std())
print(marks.mean())

row=np.array([1,2,3,4,5])
# or row=np.arange(1,6)
colume=np.array([[1],[2],[3],[4],[5]])
row*colume



8.357032966310472
81.6


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [51]:
row=np.array([1,2,3,4,5])
# or row=np.arange(1,6)
colume=np.array([[1],[2],[3],[4],[5]])
d=row*colume
print(d.flatten())

[ 1  2  3  4  5  2  4  6  8 10  3  6  9 12 15  4  8 12 16 20  5 10 15 20
 25]


In [49]:
l=np.array([[12,53,43],
            [33,32,33]])
for i in range(len(l)):
    for j in range(len(l[0])):
        if (l[i][j]<40):
            l[i][j]=0
print(l)



[[ 0 53 43]
 [ 0  0  0]]
