In [1]:
import numpy as np

# Level 1 — Basic

In [31]:
# 1. Create nums array and print details
nums = np.array([5, 10, 15, 20, 25, 30])

print("Array:", nums)
print("Shape:", nums.shape)
print("Dtype:", nums.dtype)

Array: [ 5 10 15 20 25 30]
Shape: (6,)
Dtype: int64


In [32]:
# 2. Print specific elements
print("First element:", nums[0])
print("Last element:", nums[-1])
print("Third element:", nums[2])

First element: 5
Last element: 30
Third element: 15


In [33]:
# 3. Even numbers from 0 to 20
even_nums = np.arange(0, 21, 2)
print("Even numbers:", even_nums)

Even numbers: [ 0  2  4  6  8 10 12 14 16 18 20]


In [34]:
# 4. Arrays of zeros and ones
zeros = np.zeros(5)
ones = np.ones(4)

print("Zeros array:", zeros)
print("Ones array:", ones)

Zeros array: [0. 0. 0. 0. 0.]
Ones array: [1. 1. 1. 1.]


In [35]:
# 5. Daily step counts with bonus steps
steps = np.array([4000, 5500, 6200, 7000, 4800, 5300])

bonus_steps = steps + 500

print( steps)
print("After", bonus_steps)

[4000 5500 6200 7000 4800 5300]
After [4500 6000 6700 7500 5300 5800]


In [36]:

# 6. Five evenly spaced values between 0 and 100
values = np.linspace(0, 100, 5)

print("Linspace", values)

Linspace [  0.  25.  50.  75. 100.]


# Level 2 — Intermediate

In [37]:
# 1
m = np.array([
    [80, 75, 90],
    [85, 88, 92],
    [70, 78, 82],
    [95, 91, 89]
])

print("Shape:", m.shape)
print("Size:", m.size)

Shape: (4, 3)
Size: 12


In [38]:

# 2. Second student's row and first subject's column
print("2nd student:", m[1])
print("1st subject:", m[:, 0])

2nd student: [85 88 92]
1st subject: [80 85 70 95]


In [39]:
# 3. First two students and last two subjects
print("Block:")
print(m[:2, 1:])

Block:
[[75 90]
 [88 92]]


In [40]:
# 4. Reshape arange(12)
a = np.arange(12)

a1 = a.reshape(3, 4)
a2 = a.reshape(4, 3)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [41]:
# 5. Student averages and top score in each subject
print("Avg:", m.mean(axis=1))
print("Top:", m.max(axis=0))

Avg: [81.66666667 88.33333333 76.66666667 91.66666667]
Top: [95 91 92]


In [42]:
# 6. Statistics on a 1D array
n = np.array([5, 10, 15, 20, 25, 30, 35, 40])

print("Sum:", n.sum())
print("Mean:", n.mean())
print("Min:", n.min())
print("Max:", n.max())
print("Std:", n.std())


Sum: 180
Mean: 22.5
Min: 5
Max: 40
Std: 11.4564392373896


In [43]:
# 7. Slicing examples
x = np.array([10, 20, 30, 40, 50, 60])

print(x[1:4])    
print(x[::2])    

[20 30 40]
[10 30 50]


# Level 3 — Challenge

In [44]:
# 1. Broadcasting
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

r = np.array([10, 20, 30])

b = a + r   # r is added to every row automatically

print("1.")
print(b)

1.
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [45]:
# 2. Feature Scaling (Standardization)
x = np.array([10, 20, 30, 40, 50, 60])

z = (x - x.mean()) / x.std()

print("\n2.")
print(z)
print("Mean:", z.mean())


# 3. 5x5 Multiplication Table
c = np.arange(1, 6).reshape(5, 1)
r = np.arange(1, 6)

t = c * r

print("\n3.")
print(t)


2.
[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
Mean: 0.0

3.
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [46]:
# 3. 5x5 Multiplication Table
c = np.arange(1, 6).reshape(5, 1)
r = np.arange(1, 6)

t = c * r

print("\n3.")
print(t)


3.
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [47]:

# 4. Conditional Update
m = np.array([75, 35, 90, 20, 55, 39, 80, 45, 10, 60])

print("\n4.")
print("Before:", m)

m[m < 40] = 0

print("After :", m)


4.
Before: [75 35 90 20 55 39 80 45 10 60]
After : [75  0 90  0 55  0 80 45  0 60]


In [48]:
# 5. Image Array
img = np.array([
    [0, 50, 100, 150],
    [25, 75, 125, 175],
    [50, 100, 150, 200],
    [75, 125, 175, 255]
])

f = img.flatten()
n = f / 255

print("\n5.")
print("Length:", len(f))
print("Max:", n.max())


5.
Length: 16
Max: 1.0


In [49]:
# 6. Mini Sales Analysis
s = np.array([
    [100, 200, 150, 250],
    [120, 180, 170, 220],
    [140, 210, 160, 300]
])

p = s.sum(axis=0)      # total per product
m = s.sum(axis=1)      # total per month
b = m.argmax()         # best month index

print("\n6.")
print("Product Total:", p)
print("Month Total:", m)
print("Best Month Index:", b)


6.
Product Total: [360 590 480 770]
Month Total: [700 690 810]
Best Month Index: 2
